import { VENDOR } from "./store-columns";

export const vendors: VENDOR[] = [
  {
    id: 1,
    name: "Dell Technologies",
    store: 3,
    rating: 4,
    orders: "Dec 12, 12:56 PM",
    total_spent: 23987,
    last_order: "Dec 12, 12:56 PM",
    img: "/product.jpg",
    productUrl: "/",
  },
  {
    id: 2,
    name: "Honda",
    store: 5,
    rating: 5,
    orders: "Dec 09, 10:48 AM",
    total_spent: 1250,
    last_order: "Dec 09, 10:48 AM",
    img: "/product.jpg",
    productUrl: "/",
  },
  {
    id: 3,
    name: "Xiaomi",
    store: 6,
    rating: 5,
    orders: "Dec 03, 05:45 PM",
    total_spent: 360,
    last_order: "Dec 03, 05:45 PM",
    img: "/product.jpg",
    productUrl: "/",
  },
  {
    id: 4,
    name: "Huawei Shop BD",
    store: 1,
    rating: 5,
    orders: "Nov 27, 06:20 PM",
    total_spent: 1799,
    last_order: "Nov 27, 06:20 PM",
    img: "/product.jpg",
    productUrl: "/",
  },
  {
    id: 5,
    name: "Intel",
    store: 2,
    rating: 4,
    orders: "Nov 21, 10:25 AM",
    total_spent: 65,
    last_order: "Nov 21, 10:25 AM",
    img: "/product.jpg",
    productUrl: "/",
  },
];
