/*
|-----------------------------------------
| setting up Data for the App
| @author: Toufiquer Rahman<toufiquer.0@gmail.com>
| @copyright: DaaUK, September, 2023
|-----------------------------------------
*/
import { PRODUCTS } from "./product-columns";

export const data: PRODUCTS[] = [
  {
    id: 0,
    product_name:
      "Fitbit Sense Advanced Smartwatch with Tools for Heart Health, Stress Management & Skin Temperature Trends, Carbon/Graphite, One Size (S & ...",
    price: 39,
    category: "HEALTH",
    tags: ["EXERCISE", "DISCIPLINE", "LIFESTYLE", "FITNESS"],
    vendor: "sellers.Inc",
    published_on: "Nov 12, 10:45 PM",
    img: "https://i.ibb.co/ZfzRN83/product.png",
    productUrl: "https://i.ibb.co/ZfzRN83/product.png",
    isRating: true,
  },
  {
    id: 1,
    product_name: "iPhone 13 pro max-Pacific Blue-128GB storage",
    price: 87,
    category: "FURNITURE",
    tags: ["CLASS", "CAMERA", "DISCIPLINE", "INVINCIBLE", "PRO", "SWAG"],
    vendor: "Beatrice Furnitures",
    published_on: "Nov 11, 7:36 PM",
    img: "https://i.ibb.co/ZfzRN83/product.png",
    productUrl: "https://i.ibb.co/ZfzRN83/product.png",
    isRating: false,
  },
  {
    id: 2,
    product_name: "Apple MacBook Pro 13 inch-M1-8/256GB-space",
    price: 9,
    category: "PLANTS",
    tags: ["EFFICIENCY", "HANDY", "APPLE", "CREATIVITY", "GRAY"],
    vendor: "PlantPlanet",
    published_on: "Nov 11, 8:16 AM",
    img: "https://i.ibb.co/ZfzRN83/product.png",
    productUrl: "https://i.ibb.co/ZfzRN83/product.png",
    isRating: true,
  },
  {
    id: 3,
    product_name: 'Apple iMac 24" 4K Retina Display M1 8 Core CPU...',
    price: 8 - 58,
    category: "TOYS",
    tags: ["COLOR", "STUNNING", "RETINA", "GREEN", "PC"],
    vendor: "Kizzstore",
    published_on: "Nov 8, 6:39 PM",
    img: "https://i.ibb.co/ZfzRN83/product.png",
    productUrl: "https://i.ibb.co/ZfzRN83/product.png",
    isRating: true,
  },
  {
    id: 4,
    product_name: "Razer Kraken v3 x Wired 7.1 Surroung Sound Gaming headset",
    price: 120,
    category: "FASHION",
    tags: ["MUSIC", "AUDIO", "MEETING", "RECORD", "SOUND"],
    vendor: "Inertia Fashion",
    published_on: "Nov 8, 5:32 PM",
    img: "https://i.ibb.co/ZfzRN83/product.png",
    productUrl: "https://i.ibb.co/ZfzRN83/product.png",
    isRating: false,
  },
  {
    id: 5,
    product_name: "PlayStation 5 DualSense Wireless Controller",
    price: 239,
    category: "GADGETS",
    tags: ["GAME", "CONTROL", "NAV", "PLAYSTATION", "WIRELESS"],
    vendor: "FutureTech Inc",
    published_on: "Nov 6, 11:34 PM",
    img: "https://i.ibb.co/ZfzRN83/product.png",
    productUrl: "https://i.ibb.co/ZfzRN83/product.png",
    isRating: true,
  },
  {
    id: 6,
    product_name: "2021 Apple 12.9-inch iPad Pro (Wi-Fi, 128GB) - Space Gray",
    price: 4,
    category: "FOOD",
    tags: ["IPAD", "PRO", "CREATIVITY", "THUNDERBOLT", "SPACE"],
    vendor: "Maimuna's Bakery",
    published_on: "Nov 1, 7:45 AM",
    img: "https://i.ibb.co/ZfzRN83/product.png",
    productUrl: "https://i.ibb.co/ZfzRN83/product.png",
    isRating: true,
  },
  {
    id: 7,
    product_name:
      "Amazon Basics Matte Black Wired Keyboard - US Layout (QWERTY)",
    price: 98,
    category: "FASHION",
    tags: ["KEYBOARD", "SMOOTH", "BUTTER", "RGB", "BLACK"],
    vendor: "Green fashion",
    published_on: "Nov 3, 12:27 PM",
    img: "https://i.ibb.co/ZfzRN83/product.png",
    productUrl: "https://i.ibb.co/ZfzRN83/product.png",
    isRating: false,
  },
  {
    id: 8,
    product_name: "Apple Magic Mouse (Wireless, Rechargable) - Silver",
    price: 568,
    category: "FASHION",
    tags: ["HEALTH", "EXERCISE", "DISCIPLINE", "LIFESTYLE", "FITNESS"],
    vendor: "Green fashion",
    published_on: "Nov 3, 12:27 PM",
    img: "https://i.ibb.co/ZfzRN83/product.png",
    productUrl: "https://i.ibb.co/ZfzRN83/product.png",
    isRating: true,
  },
];
